# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_id = stellaris
mod_version = 2.0.0-beta.2.6
maven_group = org.exodusstudio.stellaris
archives_name = stellaris
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
architectury_api_version = 20.0.12
fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2
neoforge_version = 26.1.2.95
potentials_version=0.9.3
modmenu_version=18.0.0
exoconfig_version=0.3.5
skyaesthetics_version=2.1.4
jei_version=29.29.0.77
jade_version=26.1.9