# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_id = stellaris
mod_version = 2.0.3
release_type = stable
maven_group = org.exodusstudio.stellaris
archives_name = stellaris
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2
supported_minecraft_versions = 26.1.2

# Dependencies
architectury_api_version = 20.1.15
fabric_loader_version = 0.19.5
fabric_api_version = 0.155.3
neoforge_version = 26.1.2.109
potentials_version=0.9.3
modmenu_version=18.0.1
exoconfig_version=0.3.5
skyaesthetics_version=2.1.4
jei_version=29.37.0.99
rei_version=26.1.819
jade_version=26.1.11