# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_id = stellaris
mod_version = 2.0.0-alpha.3
maven_group = org.exodusstudio.stellaris
archives_name = stellaris
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
architectury_api_version = 20.0.6
fabric_loader_version = 0.19.3
fabric_api_version = 0.150.0
neoforge_version = 26.1.2.71
potentials_version=0.9.0
modmenu_version=18.0.0-beta.1
exoconfig_version=0.3.2
skyaesthetics_version=2.1.0
jei_version=29.6.2.31