@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package org.exodusstudio.stellaris.neoforge.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;