@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package org.exodusstudio.stellaris.neoforge.datagen.loottables;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;