modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "stellaris"
version = "${version}"
displayName = "Stellaris"
authors = "Exodus Studio"
description = '''
Stellaris introduces an expansive and immersive space exploration experience within the familiar Minecraft universe. Players can discover new planets, moon and galaxies !
'''
#logoFile = ""

[[dependencies.stellaris]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stellaris]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stellaris]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "stellaris.mixins.json"
