architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(':common').loom.accessWidenerPath

    neoForge {
        convertAccessWideners(tasks.named('shadowJar', Jar), 'stellaris.accesswidener')
    }

    runs {
        client {
            client()
            property 'neoforge.enabledGameTestNamespaces', rootProject.mod_id
        }
    }
}

configurations {
    developmentNeoForge.extendsFrom common
}

sourceSets {
    main {
        resources.srcDir project(':common').file('src/main/generated/resources').absolutePath
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    implementation "com.fej1fun.potentials:potentials-neoforge-$rootProject.minecraft_version:$rootProject.potentials_version"
    implementation "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"

    compileOnly "mezz.jei:jei-$rootProject.minecraft_version-neoforge-api:$rootProject.jei_version"
    runtimeOnly "mezz.jei:jei-$rootProject.minecraft_version-neoforge:$rootProject.jei_version"

    runtimeOnly "maven.modrinth:jade:${rootProject.jade_version}+neoforge"

    common(project(path: ':common')) { transitive = false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionNeoForge')) { transitive = false }
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    exclude 'fabric.mod.json'
    exclude 'architectury.common.json'
}
