plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath.set(project(":common").loom.accessWidenerPath)
}

sourceSets {
    main  {
        resources.srcDir project(":common").file("src/main/generated/resources").absolutePath
    }
}


configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowCommon {
        canBeResolved = true
        canBeConsumed = false
    }

    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

loom {
    runs {
        client {
            client()
            property 'neoforge.enabledGameTestNamespaces', project.name
        }
    }
}

    repositories {
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
    }

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    implementation "com.fej1fun.potentials:potentials-neoforge-$rootProject.minecraft_version:$rootProject.potentials_version"
    implementation "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"

    common(project(path: ':common')) { transitive false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionNeoForge'))
}


processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

tasks.shadowJar {
    exclude "architectury.common.json"

    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
}

jar {
    archiveClassifier = "raw"
}
