package org.exodusstudio.stellaris;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.ToNumberPolicy;
import com.google.gson.Strictness;
import fr.tathan.exoconfig.common.loader.ConfigsRegistry;
import net.minecraft.server.MinecraftServer;
import org.apache.commons.lang3.mutable.MutableBoolean;
import org.exodusstudio.stellaris.common.config.CommonConfig;
import org.exodusstudio.stellaris.common.network.NetworkRegistry;
import org.exodusstudio.stellaris.common.registries.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class Stellaris {
    public static final String MOD_ID = "stellaris";
    public static final Logger LOG = LoggerFactory.getLogger(MOD_ID);
    public static final Gson GSON = new GsonBuilder()
            .setPrettyPrinting()
            .setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE)
            .setStrictness(Strictness.LENIENT)
            .create();
  
    public static CommonConfig CONFIG;

    public static void init() {
        CONFIG = ConfigsRegistry.getInstance().registerConfig(new CommonConfig(), CONFIG);;

        NetworkRegistry.init();

        DataComponentsRegistry.DATA_COMPONENT_TYPE.register();
        BlocksRegistry.BLOCKS.register();
        BlockEntitiesRegistry.BLOCK_ENTITY_TYPE.register();
        ItemsRegistry.ITEMS.register();
        CreativeTabsRegistry.register();
        MenuTypesRegistry.MENU_TYPE.register();
        CommandsRegistry.register();

        CapabilitiesRegistry.init();
    }

//    public static void regenWorlds(MinecraftServer server) {
//        if (!(server.getDefaultGameType().isSurvival())) {
//            @SuppressWarnings({ "CastToIncompatibleInterface", "resource" })
//            LevelStorage.Session session = ((MinecraftServer_SessionAccess)(server)).bigglobe_getSession();
//
//            MutableBoolean deletedAnything = new MutableBoolean(false);
//            RegistryVersions
//                    .getRegistry(
//                            server.getRegistryManager(),
//                            RegistryKeys.DIMENSION
//                    )
//                    .streamEntries()
//                    //only delete dimensions generated by big globe.
//                    .filter((RegistryEntry<DimensionOptions> options) -> options.value().chunkGenerator() instanceof BigGlobeScriptedChunkGenerator)
//                    .peek((RegistryEntry<DimensionOptions> options) -> LOGGER.info("Found " + MODNAME + " dimension " + UnregisteredObjectException.getKey(options)))
//                    .map((RegistryEntry<DimensionOptions> options) -> session.getWorldDirectory(
//                            RegistryKey.of(RegistryKeys.WORLD, UnregisteredObjectException.getID(options))
//                    ))
//                    .flatMap((Path dimensionFolder) ->
//                            Stream.of("advancements", "data", "entities", "playerdata", "poi", "region", "stats")
//                                    .map(dimensionFolder::resolve)
//                    )
//                    .forEach((Path toDelete) -> {
//                        if (Files.exists(toDelete)) try {
//                            deletedAnything.setTrue();
//                            PathUtils.deleteDirectory(toDelete);
//                            LOGGER.info("Deleted " + toDelete);
//                        }
//                        catch (Exception exception) {
//                            LOGGER.error("Could not delete " + toDelete, exception);
//                        }
//                    });
//            if (deletedAnything.isTrue()) {
//                Path voxy = session.getWorldDirectory(World.OVERWORLD).resolve("voxy");
//                if (Files.exists(voxy)) try {
//                    PathUtils.deleteDirectory(voxy);
//                    LOGGER.info("Deleted " + voxy);
//                }
//                catch (Exception exception) {
//                    LOGGER.error("Could not delete " + voxy, exception);
//                }
//            }
//        }
//    }
}
